version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8889:80
    depends_on:
      - app
    container_name: DataInlife_nginx

  app:
    volumes:
        - ./:/var/www
    build:
        context: .
        dockerfile: _docker/app/Dockerfile
    depends_on:
      - db
    container_name: DataInlife_app

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 8101:3306
    volumes:
      - ./tmp/db:/var/lib/mysql
    container_name: DataInlife_db
